# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gd2-ffij}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = %q{2010-02-04}
  s.description = %q{gd2-ffij is refactoring of the Ruby/GD2 library implemented with FFI}
  s.email = %q{dark.panda@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "COPYING",
     "COPYRIGHT",
     "README",
     "Rakefile",
     "lib/gd2-ffij.rb",
     "lib/gd2/canvas.rb",
     "lib/gd2/color.rb",
     "lib/gd2/ffi_struct.rb",
     "lib/gd2/font.rb",
     "lib/gd2/image.rb",
     "lib/gd2/palette.rb",
     "test/canvas_test.rb",
     "test/image_test.rb",
     "test/images/test.bmp",
     "test/images/test.gd",
     "test/images/test.gd2",
     "test/images/test.gif",
     "test/images/test.jpg",
     "test/images/test.png",
     "test/images/test.wbmp",
     "test/images/test.xbm",
     "test/images/test.xcf",
     "test/images/test.xpm",
     "test/images/test_canvas_filled_polygon.gd2",
     "test/images/test_canvas_filled_rectangle.gd2",
     "test/images/test_canvas_line.gd2",
     "test/images/test_canvas_move_to_and_line_to.gd2",
     "test/images/test_canvas_polygon.gd2",
     "test/images/test_canvas_rectangle.gd2",
     "test/images/test_color.gd2",
     "test/images/test_color.png",
     "test/images/test_color.xcf",
     "test/images/test_color_indexed.gd2",
     "test/images/test_color_sharpened.gd2",
     "test/images/test_cropped.gd2",
     "test/images/test_polar_transform.gd2",
     "test/images/test_resampled.gd2",
     "test/images/test_resized.gd2",
     "test/images/test_rotated_180.gd2",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/dark.panda/gd2-ffij}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{gd2-ffij is refactoring of the Ruby/GD2 library implemented with FFI}
  s.test_files = [
    "test/canvas_test.rb",
     "test/image_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

