# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gd2-ffij"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = "2012-01-03"
  s.description = "gd2-ffij is a refactoring of the Ruby/GD2 library implemented with FFI"
  s.email = "dark.panda@gmail.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "COPYING",
    "COPYRIGHT",
    "README",
    "Rakefile",
    "VERSION",
    "gd2-ffij.gemspec",
    "lib/gd2-ffij.rb",
    "lib/gd2/canvas.rb",
    "lib/gd2/color.rb",
    "lib/gd2/ffi_struct.rb",
    "lib/gd2/font.rb",
    "lib/gd2/image.rb",
    "lib/gd2/palette.rb",
    "test/canvas_tests.rb",
    "test/image_tests.rb",
    "test/images/test.bmp",
    "test/images/test.gd",
    "test/images/test.gd2",
    "test/images/test.gif",
    "test/images/test.jpg",
    "test/images/test.png",
    "test/images/test.wbmp",
    "test/images/test.xbm",
    "test/images/test.xcf",
    "test/images/test.xpm",
    "test/images/test_arc.gd2",
    "test/images/test_canvas_filled_polygon.gd2",
    "test/images/test_canvas_filled_rectangle.gd2",
    "test/images/test_canvas_line.gd2",
    "test/images/test_canvas_move_to_and_line_to.gd2",
    "test/images/test_canvas_polygon.gd2",
    "test/images/test_canvas_rectangle.gd2",
    "test/images/test_circle.gd2",
    "test/images/test_color.gd2",
    "test/images/test_color.png",
    "test/images/test_color.xcf",
    "test/images/test_color_indexed.gd2",
    "test/images/test_color_sharpened.gd2",
    "test/images/test_cropped.gd2",
    "test/images/test_ellipse.gd2",
    "test/images/test_fill.gd2",
    "test/images/test_fill_to.gd2",
    "test/images/test_filled_circle.gd2",
    "test/images/test_filled_ellipse.gd2",
    "test/images/test_filled_wedge.gd2",
    "test/images/test_polar_transform.gd2",
    "test/images/test_resampled.gd2",
    "test/images/test_resized.gd2",
    "test/images/test_rotated_180.gd2",
    "test/images/test_text.gd2",
    "test/images/test_text_circle.gd2",
    "test/images/test_wedge.gd2",
    "test/test_helper.rb",
    "vendor/fonts/ttf/DejaVuSans.ttf",
    "vendor/fonts/ttf/LICENSE"
  ]
  s.homepage = "http://github.com/dark-panda/gd2-ffij"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "gd2-ffij is a refactoring of the Ruby/GD2 library implemented with FFI"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<ffi>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 1.0.0"])
  end
end

